jobs:
  npm:
    name: NPM
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        registry-url: https://registry.npmjs.org
    - continue-on-error: true
      name: Install dependencies
      run: yarn --frozen-lockfile --non-interactive --silent
    - continue-on-error: true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      name: Publish to NPM
      run: npm publish
name: Deploy
on:
  repository_dispatch:
    types: trigger-ga___deploy.yaml
